title = "IFAISE2020"
baseURL = "http://ifaise2020.edtechstar.com/"
languageCode = "en-us"
theme = "gohugo-theme-ananke"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
defaultContentLanguageInSubdir = true
enableGitInfo = true
# relativeURLs = true


[markup]
  [markup.goldmark.renderer]
    unsafe= true
  [markup.tableOfContents]
    endLevel = 2
    ordered = false
    startLevel = 2


[languages]
  [languages.en]
    title = "IFAISE2020"
    weight = 1
    LanguageName = "English"
    Copyright = "Shaanxi Normal University"
    [languages.en.params]
      description = "Xi'an China, Dec 26, 2020"
      madewith = "❤️ Made with Hugo, <a class='white-70' href='https://github.com/jizusun/zbh-conferences'>GitHub</a>, and <a class='white-70' href='/admin'>Forestry</a>"
  [languages.zh]
    title = "IFAISE2020"
    weight = 2
    LanguageName = "中文"
    Copyright = "陕西师范大学"
    [languages.zh.params]
      description = "中国西安, 2020年12月26日"
      madewith = "❤️ 使用 Hugo, <a class='white-70' href='https://github.com/jizusun/zbh-conferences'>GitHub</a> 和 <a class='white-70' href='/admin'>Forestry</a> 创作"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = "images/favicon.ico"
  site_logo = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/banner.jpg"
  recent_posts_number = 2
  netlify_badge = "<a href='https://app.netlify.com/sites/ifaise2020/deploys'><img src='https://api.netlify.com/api/v1/badges/4634a633-c8fc-4160-9a8c-88c9c8d4240a/deploy-status'/></a> "